version: "3.9"

services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rps_rmq_data:/var/lib/rabbitmq

  subtraction:
    build: 
        dockerfile: SubtractService/Dockerfile
        context: .
    depends_on:
        - rmq
        - zipkin
        - seq
    deploy:
      replicas: 3

  addition:
    build: 
        dockerfile: AdditionService/Dockerfile
        context: .
    depends_on:
        - rmq
        - zipkin
        - seq
    deploy:
      replicas: 3

volumes:
  rps_seq_data:
  rps_rmq_data: